Feature/cplp 843/show all data
catenax-ng/product-portal-frontend-registration pull request #26
Opened 2022-06-15 12:29 UTC by nidhigarg-bmw

2022-06-26 21:05 UTC, jjeroch reviewed
Looks good. Only one minor request added regarding the application status "CREATED"

2022-06-27 04:25 UTC, nidhigarg-bmw commented on src/components/dragdrop.tsx
> +  const obj = status[status.length-1] //.find(o => o['applicationStatus'] === CREATED);
@jjeroch Actually this status get updated on landing page due to which we not to track "obj" according to status "CREATED" on other steps of registration form.

2022-06-27 10:49 UTC, oyo requested changes

2022-06-27 10:49 UTC, oyo commented on src/components/dragdrop.tsx
> -            : t(`ErrorMessage.default`)
you could call that key `ErrorMessage.undefined` then you don't need the  ? :  operator and can just go with line 50

2022-06-27 10:49 UTC, oyo commented on src/components/dragdrop.tsx
> +            documents.map((document: any, index) =>
we should avoid using `any` - is there no type for `document` defined?

2022-06-27 10:49 UTC, oyo commented on src/components/verifyRegistration.tsx
> +  console.log('registrationData', registrationData)
`console.log` statements like this we can use during development but they should be removed before commit

2022-06-27 10:49 UTC, oyo commented on src/components/verifyRegistration.tsx
> +  const obj = status[status.length-1] //.find(o => o['applicationStatus'] === CREATED);
that comment should be removed or add a `TODO` comment if you want to activate that later

2022-06-27 10:49 UTC, oyo commented on src/components/verifyRegistration.tsx
> +                  <span className="col-6">{registrationData?.streetName}{' '}{registrationData?.streetNumber}</span>
I think the `}{' '}{` can be written as `} {`

2022-06-27 10:49 UTC, oyo commented on src/components/verifyRegistration.tsx
> +                  <span className="col-6">{registrationData?.zipCode}{' '}{registrationData?.city}</span>
see comment above

2022-06-27 10:49 UTC, oyo commented on src/state/features/applicationDocuments/api.ts
> +      headers: {
use `RequestService.getHeaders()` here just like above in line 23

2022-06-27 10:49 UTC, oyo commented on src/state/features/applicationVerifyRegister/api.ts
> +        headers: {
use `RequestService.getHeaders()`

2022-06-27 10:49 UTC, oyo commented on src/state/features/applicationVerifyRegister/api.ts
> +        headers: {
use `RequestService.getHeaders()`

2022-06-28 14:48 UTC, nidhigarg-bmw commented
Hi @oyo 
Please review this PR again. I made the changes.

2022-06-29 11:33 UTC, oyo approved these changes
looks good now

2022-06-29 11:37 UTC, merged