Registration closed functionality
catenax-ng/product-portal-frontend-registration pull request #27
Opened 2022-06-17 11:23 UTC by lavanya-bmw

2022-06-22 06:06 UTC, jjeroch requested changes

2022-06-22 06:06 UTC, jjeroch commented on src/styles/newApp.css
> +  background: #f8f8f8 !important;
@lavanya-bmw this is without any background transparency, right? Can we please change this to "white"

2022-06-22 07:05 UTC, nidhigarg-bmw approved these changes
Looks good to me

2022-06-27 07:16 UTC, oyo approved these changes
looks good to me :)

2022-06-27 12:50 UTC, jjeroch approved these changes

2022-06-28 12:21 UTC, jjeroch commented
@lavanya-bmw can you recheck the merge conflicts?

2022-06-30 11:50 UTC, merged

2022-06-30 11:50 UTC, jjeroch commented
@lavanya-bmw I merged the change. Hope thats fine