Fix/cplp 1187/submit btn issue
catenax-ng/product-portal-frontend-registration pull request #37
Opened 2022-07-19 08:47 UTC by nidhigarg-bmw

2022-07-20 07:47 UTC, oyo requested changes
some changes required - especially there is no error handling

2022-07-20 07:47 UTC, oyo commented on src/components/dragdrop.tsx
> +      toast.error('...')
please add the according error message here - also the i18n is missing

2022-07-20 07:47 UTC, oyo commented on src/components/dragdrop.tsx
> +    console.log('allFiles', allFiles)
please remove console logs before PR

2022-07-20 07:47 UTC, oyo commented on src/components/dragdrop.tsx
> +      toast.error('Only .pdf files are allowed')
please use translations here

2022-07-20 07:47 UTC, oyo commented on src/components/dragdrop.tsx
>      toast.success('All files uploaded')
this is not a good error handling - with `dispatch` we only trigger the action. But we don't know if the `saveDocument` call was successful or not. So instead listen to the result of the upload using `useSelector` - then show a message if the upload was successful or not

2022-07-20 08:27 UTC, oyo commented
more details about the error handling:
- get the result of the upload action with `useSelector(stateSelector)` from the applicationDocuments slice
- show a success toast when `.uploadRequest` is `'true'` otherwise show an error toast

2022-07-20 11:58 UTC, jjeroch commented
> more details about the error handling:
> 
> * get the result of the upload action with `useSelector(stateSelector)` from the applicationDocuments slice
> * show a success toast when `.uploadRequest` is `'true'` otherwise show an error toast

Quick point on this. I dont want a success toast please. We push the user to the next window, so a success message is not needed on top. That would be a double message. Regarding the error, I fully agree

2022-07-20 12:21 UTC, nidhigarg-bmw commented
> > more details about the error handling:
> > 
> > * get the result of the upload action with `useSelector(stateSelector)` from the applicationDocuments slice
> > * show a success toast when `.uploadRequest` is `'true'` otherwise show an error toast
> 
> Quick point on this. I dont want a success toast please. We push the user to the next window, so a success message is not needed on top. That would be a double message. Regarding the error, I fully agree
@jjeroch Okay, I have removed the success message and showing only error message if any.

2022-07-21 09:05 UTC, oyo approved these changes
looks good to me now

2022-07-21 12:25 UTC, merged