Feature/cplp 606/user name issue
catenax-ng/product-portal-frontend-registration pull request #8
Opened 2022-05-05 08:38 UTC by nidhigarg-bmw

2022-05-09 12:23 UTC, oyo requested changes

2022-05-09 12:23 UTC, oyo commented on src/helpers/UserService.js
> +const getUsername = () => _kc.tokenParsed?.given_name
please don't use just given_name because we also have family_name. Check the token attributes for different users at https://portal.dev.demo.catena-x.net/account 
I think we should go with:
`'${_kc.tokenParsed?.given_name} ${_kc.tokenParsed?.family_name}'`
(replace ' with a backtick `)

2022-05-09 12:51 UTC, nidhigarg-bmw commented on src/helpers/UserService.js
> +const getUsername = () => _kc.tokenParsed?.given_name
@oyo I made the changes. Please check again.

2022-05-11 11:29 UTC, oyo approved these changes
looks good now :)

2022-05-11 11:38 UTC, merged